/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReposRepoIdRouteImport } from './routes/repos.$repoId'
import { Route as ReposRepoIdIndexRouteImport } from './routes/repos.$repoId.index'
import { Route as ReposRepoIdDiffRefRouteImport } from './routes/repos.$repoId.diff.$ref'
import { Route as ReposRepoIdNotesNoteNameRouteImport } from './routes/repos.$repoId.notes.$noteName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposRepoIdRoute = ReposRepoIdRouteImport.update({
  id: '/repos/$repoId',
  path: '/repos/$repoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposRepoIdIndexRoute = ReposRepoIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReposRepoIdRoute,
} as any)
const ReposRepoIdDiffRefRoute = ReposRepoIdDiffRefRouteImport.update({
  id: '/diff/$ref',
  path: '/diff/$ref',
  getParentRoute: () => ReposRepoIdRoute,
} as any)
const ReposRepoIdNotesNoteNameRoute =
  ReposRepoIdNotesNoteNameRouteImport.update({
    id: '/notes/$noteName',
    path: '/notes/$noteName',
    getParentRoute: () => ReposRepoIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/repos/$repoId': typeof ReposRepoIdRouteWithChildren
  '/repos/$repoId/': typeof ReposRepoIdIndexRoute
  '/repos/$repoId/diff/$ref': typeof ReposRepoIdDiffRefRoute
  '/repos/$repoId/notes/$noteName': typeof ReposRepoIdNotesNoteNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/repos/$repoId': typeof ReposRepoIdIndexRoute
  '/repos/$repoId/diff/$ref': typeof ReposRepoIdDiffRefRoute
  '/repos/$repoId/notes/$noteName': typeof ReposRepoIdNotesNoteNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/repos/$repoId': typeof ReposRepoIdRouteWithChildren
  '/repos/$repoId/': typeof ReposRepoIdIndexRoute
  '/repos/$repoId/diff/$ref': typeof ReposRepoIdDiffRefRoute
  '/repos/$repoId/notes/$noteName': typeof ReposRepoIdNotesNoteNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/repos/$repoId'
    | '/repos/$repoId/'
    | '/repos/$repoId/diff/$ref'
    | '/repos/$repoId/notes/$noteName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/repos/$repoId'
    | '/repos/$repoId/diff/$ref'
    | '/repos/$repoId/notes/$noteName'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/repos/$repoId'
    | '/repos/$repoId/'
    | '/repos/$repoId/diff/$ref'
    | '/repos/$repoId/notes/$noteName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  ReposRepoIdRoute: typeof ReposRepoIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$repoId': {
      id: '/repos/$repoId'
      path: '/repos/$repoId'
      fullPath: '/repos/$repoId'
      preLoaderRoute: typeof ReposRepoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$repoId/': {
      id: '/repos/$repoId/'
      path: '/'
      fullPath: '/repos/$repoId/'
      preLoaderRoute: typeof ReposRepoIdIndexRouteImport
      parentRoute: typeof ReposRepoIdRoute
    }
    '/repos/$repoId/diff/$ref': {
      id: '/repos/$repoId/diff/$ref'
      path: '/diff/$ref'
      fullPath: '/repos/$repoId/diff/$ref'
      preLoaderRoute: typeof ReposRepoIdDiffRefRouteImport
      parentRoute: typeof ReposRepoIdRoute
    }
    '/repos/$repoId/notes/$noteName': {
      id: '/repos/$repoId/notes/$noteName'
      path: '/notes/$noteName'
      fullPath: '/repos/$repoId/notes/$noteName'
      preLoaderRoute: typeof ReposRepoIdNotesNoteNameRouteImport
      parentRoute: typeof ReposRepoIdRoute
    }
  }
}

interface ReposRepoIdRouteChildren {
  ReposRepoIdIndexRoute: typeof ReposRepoIdIndexRoute
  ReposRepoIdDiffRefRoute: typeof ReposRepoIdDiffRefRoute
  ReposRepoIdNotesNoteNameRoute: typeof ReposRepoIdNotesNoteNameRoute
}

const ReposRepoIdRouteChildren: ReposRepoIdRouteChildren = {
  ReposRepoIdIndexRoute: ReposRepoIdIndexRoute,
  ReposRepoIdDiffRefRoute: ReposRepoIdDiffRefRoute,
  ReposRepoIdNotesNoteNameRoute: ReposRepoIdNotesNoteNameRoute,
}

const ReposRepoIdRouteWithChildren = ReposRepoIdRoute._addFileChildren(
  ReposRepoIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ReposRepoIdRoute: ReposRepoIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
